trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

variables:
  IxDevOpsBuild: true
  IxVersionPrefix: 1.0.0
  IxVersionSuffix: 'beta'
  disable.coverage.autogenerate: true
  system.debug: false

# Jobs should run in parallel

resources:
  repositories:
    - repository: templates
      type: github
      name: adimosh/IX.Framework.Operations
      endpoint: adimosh

jobs:
- job:
  workspace:
    clean: all
  timeoutInMinutes: 40
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
  steps:
  - template: yaml/job-master-build.yml@templates
    parameters:
      solutionName: 'IX.Math'
- job:
  workspace:
    clean: all
  timeoutInMinutes: 20
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - template: yaml/install-dotnetcore.yml@templates
  - task: DotNetCoreCLI@2
    displayName: 'Build pre-process'
    inputs:
      command: custom
      custom: msbuild
      projects: src/IX.Math/IX.Math.csproj
      arguments: '-pp:m.ppresult.xml'
  - task: DotNetCoreCLI@2
    displayName: 'Build pre-process'
    inputs:
      command: custom
      custom: msbuild
      projects: src/IX.UnitTests/IX.UnitTests.csproj
      arguments: '-pp:t.ppresult.xml'
  - task: CopyFiles@2
    inputs:
      contents: '*.result.xml'
      targetFolder: '$(Build.ArtifactStagingDirectory)/preprocess'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish NuGet package artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/preprocess'
      ArtifactName: Preprocess
  - template: yaml/build-solution.yml@templates
    parameters:
      solutionName: 'IX.Math'
  - template: yaml/test-solution.yml@templates
  - template: yaml/clean-solution.yml@templates
    parameters:
      solutionName: 'IX.Math'
  - template: yaml/build-solution.yml@templates
    parameters:
      solutionName: 'IX.Math'
      configurationName: 'Release'
  - template: yaml/test-solution.yml@templates
    parameters:
      configurationName: 'Release'
  - template: yaml/code-coverage.yml@templates
- job:
  workspace:
    clean: all
  timeoutInMinutes: 20
  pool:
    name: Azure Pipelines
    vmImage: macOS-latest
  steps:
  - template: yaml/job-master-build.yml@templates
    parameters:
      solutionName: 'IX.Math'