trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

pr:
  autoCancel: true
  branches:
    include:
    - dev
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

variables:
  IxDevOpsBuild: true
  IxVersionPrefix: 1.0.0
  IxVersionSuffix: 'beta'
  disable.coverage.autogenerate: true
  system.debug: false

# Jobs should run in parallel

resources:
  repositories:
    - repository: templates
      type: github
      name: adimosh/IX.Framework.Operations
      endpoint: adimosh

jobs:
- job:
  timeoutInMinutes: 40
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
  steps:
  - template: yaml/job-dev-build.yml@templates
    parameters:
      solutionName: 'IX.Math'
- job:
  timeoutInMinutes: 20
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - template: yaml/job-dev-build.yml@templates
    parameters:
      solutionName: 'IX.Math'
- job:
  timeoutInMinutes: 20
  pool:
    name: Azure Pipelines
    vmImage: macOS-latest
  steps:
  - template: yaml/job-dev-build.yml@templates
    parameters:
      solutionName: 'IX.Math'